### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by liuedfie234** [marckhoury/CGF#3]
Hi,
I got this problem

> python compress.py out.lzf 2244 out.npz

Traceback (most recent call last):
  File "compress.py", line 47, in <module>
    main(sys.argv[1:])
  File "compress.py", line 39, in main
    data = decompress(features_path, 'd', 8, feature_len)
  File "compress.py", line 22, in decompress
    byte_array = f.read()
  File "/home/yzl/anaconda3/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
 UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe0 in position 3: invalid continuation byte

how could I do?
thanks !

**Comment by JoyMazumder** [comment]
Getting the same error. Any Solution?

**Comment by qsisi** [comment]
same error! waiting for solutions!

**Comment by qsisi** [comment]
> Hi,
> I got this problem
> 
> > python compress.py out.lzf 2244 out.npz
> 
> Traceback (most recent call last):
> File "compress.py", line 47, in
> main(sys.argv[1:])
> File "compress.py", line 39, in main
> data = decompress(features_path, 'd', 8, feature_len)
> File "compress.py", line 22, in decompress
> byte_array = f.read()
> File "/home/yzl/anaconda3/lib/python3.6/codecs.py", line 321, in decode
> (result, consumed) = self._buffer_decode(data, self.errors, final)
> UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe0 in position 3: invalid continuation byte
> 
> how could I do?
> thanks !

It looks like the error comes from the python3.x , in my ubuntu16.04 the default python version is  2.7, and I can run compress.py without error, maybe you can try creating a new environment with python2.7 and run again.
